'use client';

import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import { getProjects } from '@/lib/projects';
import type { Project } from '@/lib/types';
import { LoopVideo } from './LoopVideo';

/**
 * Work grid — the studio's proof, shown still and calm.
 *
 * A plain three-column grid (two on mobile): image, project name, category.
 * Motion is earned, not ambient — each tile's campaign loop plays on hover
 * (pointer devices) or while the tile is mostly in view (touch devices), and
 * never under prefers-reduced-motion. Tiles load ~100KB derivatives from
 * /studio/tiles/, not the full-res campaign frames.
 */

// Display derivatives generated by site/scripts/make-tiles.sh.
const tileSrc = (cover: string) => cover.replace('/studio/', '/studio/tiles/');

function WorkTile({ project }: { project: Project }) {
  const ref = useRef<HTMLDivElement>(null);
  const [hovered, setHovered] = useState(false);
  const [inView, setInView] = useState(false);
  const [touchDevice, setTouchDevice] = useState(false);
  const [reduceMotion, setReduceMotion] = useState(false);

  useEffect(() => {
    setTouchDevice(window.matchMedia('(hover: none)').matches);
    setReduceMotion(window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const io = new IntersectionObserver(
      ([entry]) => setInView(entry.intersectionRatio >= 0.6),
      { threshold: [0, 0.6] }
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);

  const playing =
    !reduceMotion && !!project.coverVideo && (touchDevice ? inView : hovered);

  return (
    <figure className="m-0">
      <div
        ref={ref}
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        className="relative aspect-[4/5] rounded-2xl overflow-hidden bg-stone-200"
      >
        <Image
          src={tileSrc(project.cover)}
          alt={project.images[0]?.alt ?? `${project.name} — ${project.category}`}
          fill
          sizes="(min-width: 768px) 33vw, 50vw"
          className="object-cover"
        />
        {project.coverVideo && (
          <LoopVideo
            src={project.coverVideo}
            poster={tileSrc(project.cover)}
            playing={playing}
            className="absolute inset-0 w-full h-full object-cover outline-none border-0 scale-[1.005]"
          />
        )}
      </div>
      <figcaption className="mt-space-2 text-body text-ink">
        {project.name} <span className="text-ink/70">— {project.category}</span>
      </figcaption>
    </figure>
  );
}

export function Carousel() {
  const projects = getProjects();

  return (
    <section id="work" className="bg-paper py-space-8 px-space-4">
      <div className="mx-auto max-w-6xl">
        <div className="mb-space-6 text-center">
          <div className="text-kicker text-bottle mb-space-2">Studio</div>
          <h2 className="text-h1 text-ink">
            The look<span className="text-bottle">.</span> The feel
            <span className="text-bottle">.</span>
          </h2>
          <p className="text-body text-ink/70 mt-space-3 max-w-xl mx-auto">
            Studio series — concept campaigns shot from our own briefs, to show
            the range. Your campaign follows yours.
          </p>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-x-space-3 gap-y-space-5">
          {projects.map((p) => (
            <WorkTile key={p.slug} project={p} />
          ))}
        </div>
      </div>
    </section>
  );
}
